---
bash_aliases: {}
bash_exports: {}
bash_functions: {}
bash_path_pre: []
bash_path_post: []
bash_ssh_agent: false
bash_sources: []

bash_custom_prompt: true
bash_custom_my_prompt: false

bash_editor: vim

bash_history_options: "{{ history_options['zshrc'] if bash_zsh else history_options['bash'] }}"

bash_history_time_format: "[%F %T] "
bash_history_size: 10000
bash_history_file_size: 10000

bash_rc_file: "{{ '.zshrc' if bash_zsh else '.bashrc' }}"

bash_pager: less -X

bash_zsh: "{{ true if config_os_family == 'Darwin' else false }}"

history_options:
  bash:
    - histappend
    - histverify
  zshrc:
    - EXTENDED_HISTORY
    - HIST_IGNORE_ALL_DUPS
    - HIST_IGNORE_SPACE
    - HIST_VERIFY
    - INC_APPEND_HISTORY
    - SHARE_HISTORY
