---
- name: Config setup playbook
  hosts: "{{ targets | default('localhost') }}"
  become: "{{ switch_user | default(false) }}"

  tasks:
    - name: Import grnoc_user
      ansible.builtin.include_role:
        name: globalnoc.common.grnoc_user
        public: true

    - name: Setup bash profile
      ansible.builtin.import_role:
        name: bash
      when: '"bash" in task_list'

    - name: Setup gitconfig
      ansible.builtin.import_role:
        name: gitconfig
      when: '"gitconfig" in task_list'

    - name: Setup perltidy
      ansible.builtin.import_role:
        name: perltidy
      when: '"perltidy" in task_list'

    - name: Setup ssh configs
      ansible.builtin.import_role:
        name: ssh
      when: '"ssh" in task_list'

    - name: Setup tmux config
      ansible.builtin.import_role:
        name: tmux
      when:
        - '"tmux" in task_list'
        - use_tmux | default(false)

    - name: Setup vim
      ansible.builtin.import_role:
        name: vim
      when: '"vim" in task_list'
