---
- name: Config setup playbook
  hosts: "{{ targets | default('localhost') }}"
  become: "{{ switch_user | default(false) }}"
  become_user: "{{ awx_user_name | default('root') }}"

  tasks:
    - name: Setup bash profile
      ansible.builtin.import_role:
        name: bash

    - name: Setup gitconfig
      ansible.builtin.import_role:
        name: gitconfig

    - name: Setup perltidy
      ansible.builtin.import_role:
        name: perltidy

    - name: Setup ssh configs
      ansible.builtin.import_role:
        name: ssh

    - name: Setup tmux config
      ansible.builtin.import_role:
        name: tmux
      when: use_tmux | default(false)

    - name: Setup vim
      ansible.builtin.import_role:
        name: vim
