---
ssh_host_configs:
  jdratlif-dev8.grnoc.iu.edu:
    RemoteForward:
      - '*:1080 localhost:8080'
      - '*:1081 localhost:8081'
      - '*:1082 localhost:8082'
      - '*:1083 localhost:8083'
  xaiver:
    Hostname: xaiver.technoplaza.net
    Port: 5122
    LocalForward:
      - 13389 192.168.1.6:3389
      - 3128 192.168.1.4:3128
      - 8006 192.168.1.4:8006

ssh_vscode_hosts:
  jdratlif-dev8.grnoc.iu.edu:
    Port: 10001
  awx.grnoc.iu.edu:
    port: 10002
  puppet.grnoc.iu.edu:
    port: 10003
  puppet7.grnoc.iu.edu:
    port: 10004
  awx.bldc.nwave.noaa.gov:
    port: 20001
  puppet.nwave.noaa.gov:
    port: 20002
  puppet7.bldc.nwave.noaa.gov:
    port: 20003
