---
# additional names outside the official name in the DB to assign to a host
aliases:
  build-new.grnoc.iu.edu:
    - build.grnoc.iu.edu
    - puppet.grnoc.iu.edu
  jdratlif-dev8.bldc.grnoc.iu.edu:
    - jdratlif-dev8.grnoc.iu.edu
  puppet7.bldc.nwave.noaa.gov:
    - puppet7.nwave.noaa.gov

# groups to associate withh host patterns
groups:
  awx:
    regex: "awx(?:-(?:stage|test))?\\."
  dev:
    regex: "[a-zA-Z]{4,}[-.]dev[0-9]*\\."
    grnoc:
      remove:
        - asterisk-dev1.grnoc.iu.edu
        - asterisk-dev2.grnoc.iu.edu
        - kerb-dev.grnoc.iu.edu
        - ldap-dev2.grnoc.iu.edu
        - radius-dev.grnoc.iu.edu
        - radius-dev2.grnoc.iu.edu
        - netdisco-dev.grnoc.iu.edu
        - percona-dev.grnoc.iu.edu
        - percona-dev2.grnoc.iu.edu
        - containerlab-dev.grnoc.iu.edu
        - mongo-dev.bldc.grnoc.iu.edu
        - nddi-dev.grnoc.iu.edu
        - netsage-dev.grnoc.iu.edu
        - perfsonar-dev4.grnoc.iu.edu
        - perfsonar-dev8.grnoc.iu.edu
        - perfsonar-dev9.grnoc.iu.edu
    i2:
      remove:
        - nddi-dev.bldc.net.internet2.edu
        - nddi-dev2.bldc.net.internet2.edu
  puppet:
    regex: "(?:build|puppet)"

# additional hosts to include in the inventory
other:
  home:
    ansible_connection: local
  laptop:
    ansible_connection: local
  wsl:
    ansible_connection: local
