---
ssh_authorized_keys: []
ssh_bastion_config: false
ssh_canonical_dots: 2
ssh_host_configs: {}

ssh_host_common_configs:
  ServerAliveCountMax: 3
  ServerAliveInterval: 30
  User: "{{ grnoc_user }}"

ssh_vscode_hosts: {}
