---
- name: Copy perltidyrc
  ansible.builtin.copy:
    src: perltidyrc
    backup: true
    dest: "{{ grnoc_home_dir }}/.perltidyrc"
    owner: "{{ grnoc_user }}"
    group: "{{ grnoc_user }}"
    mode: "0644"
