---
- name: Create config directories
  ansible.builtin.file:
    state: directory
    path: "{{ config_home_dir }}/.config/{{ item }}"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
    recurse: true
  loop:
    - bumblebee-status
    - i3

- name: Create venvs directory
  ansible.builtin.file:
    state: directory
    path: "{{ config_home_dir }}/venvs"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
    mode: "0755"

- name: Copy bumblebee-status requirements.txt
  ansible.builtin.copy:
    src: bumblebee-status/requirements.txt
    dest: /tmp/bumblebee-status-requirements.txt
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
    mode: "0644"

- name: Create bumblebee-status venv
  ansible.builtin.pip:
    requirements: /tmp/bumblebee-status-requirements.txt
    virtualenv: "{{ config_home_dir }}/venvs/bumblebee"

- name: Create bumblebee-status themes directory symlink
  ansible.builtin.file:
    state: link
    src: "{{ config_home_dir }}/venvs/bumblebee/share/bumblebee-status/themes"
    dest: "{{ config_home_dir }}/.config/bumblebee-status/themes"

- name: Template i3 config
  ansible.builtin.template:
    src: i3/config.sh.j2
    backup: true
    dest: "{{ config_home_dir }}/.config/i3/config"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
    mode: "0644"
