---
- name: Template tmux.conf
  ansible.builtin.template:
    src: tmux.conf.j2
    backup: true
    dest: "{{ grnoc_home_dir }}/.tmux.conf"
    owner: "{{ grnoc_user }}"
    group: "{{ grnoc_user }}"
    mode: "0644"
