---
- name: Template tmux.conf
  ansible.builtin.template:
    src: tmux.conf.j2
    backup: true
    dest: "{{ config_home_dir }}/.tmux.conf"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
    mode: "0644"
