---
gitconfig:
  name: John Ratliff
  email: jdratlif@globalnoc.iu.edu
  credentials:
    - name: https://github.grnoc.iu.edu
      username: jdratlif
      helper: cache --timeout 14400
    - name: https://github.nwave.noaa.gov
      username: jdratlif
      helper: cache --timeout 14400
