---
- name: Ensure sway config directory
  ansible.builtin.file:
    state: directory
    path: "{{ config_home_dir }}/.config/sway"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
    recurse: true

- name: Copy clamshell.sh script
  ansible.builtin.copy:
    src: clamshell.sh
    dest: "{{ config_home_dir }}/.local/bin/clamshell.sh"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
    mode: "0755"

- name: Copy sway config
  ansible.builtin.template:
    src: config.j2
    backup: true
    dest: "{{ config_home_dir }}/.config/sway/config"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
    mode: "0644"
