---
aliases:
  vpn: >-
    sudo openconnect
    -u {{ grnoc_user }}
    --protocol=pulse
    -s "vpn-slice 10.0.0.0/8 {{ vpn_hosts | join(' ') }}"
    https://vpn.iu.edu/groups

gitconfig:
  name: "John Ratliff"
  email: "john@technoplaza.net"
  credentials:
    - name: https://github.grnoc.iu.edu
      username: "{{ grnoc_user }}"
      helper: cache --timeout 14400

ssh_vscode_hosts:
  jdratlif-dev7.grnoc.iu.edu:
    port: 10001
  awx.grnoc.iu.edu:
    port: 10002
  puppet7.grnoc.iu.edu:
    port: 10003
  awx.bldc.nwave.noaa.gov:
    port: 20001
  puppet7.bldc.nwave.noaa.gov:
    port: 20002
  cobbler.bldc.nwave.noaa.gov:
    port: 20003

use_tmux: true

vpn_hosts:
  # AAA web application hosts
  - weblogin.grnoc.iu.edu
  - otp.grnoc.iu.edu
  - cosign.areon.net
  - weblogin.net.cen.ct.gov
  - account.net.internet2.edu
  - account.noc.onenet.net
  - weblogin.oshean.org
  - account.nwave.noaa.gov
  - account.scinet.usda.gov

  # AWX hosts
  - awx.grnoc.iu.edu
  - awx.bldc.nwave.noaa.gov
  - awx.ctc.nwave.noaa.gov

  # Cobbler
  - build.grnoc.iu.edu

  # GHE
  - github.nwave.noaa.gov

  # MCNC
  - db.ncren.net
  - db-test.ncren.net
  - footprints.ncren.net

  # OpenStack / VMware
  - cloud.bldc.grnoc.iu.edu
  - cloud.ctc.grnoc.iu.edu
  - cloud.bldc.scinet.usda.gov
  - cloud.ctc.scinet.usda.gov
  - vmware-test.grnoc.iu.edu

  # Tenable
  - tenable.ctc.nwave.noaa.gov
