---
- name: Copy vimrc
  ansible.builtin.copy:
    src: main.vim
    dest: "{{ ansible_user_dir }}/.vimrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"

- name: Ensure ownership of viminfo
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.viminfo"
    state: file
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  failed_when: false

- name: Create vim directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.vim"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"

- name: Copy yaml plugin
  ansible.builtin.copy:
    src: plugins/yaml.vim
    dest: "{{ ansible_user_dir }}/.vim"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"
