---
- name: Template gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    backup: true
    dest: "{{ grnoc_home_dir }}/.gitconfig"
    owner: "{{ grnoc_user }}"
    group: "{{ grnoc_user }}"
    mode: "0644"
